[package]
name = "boatbomber/sheetvalues"
description = "Use Google Sheets as a live value updater for Roblox games."
version = "3.0.2"
license = "MIT"
authors = ["boatbomber (https://boatbomber.com)"]
registry = "https://github.com/upliftgames/wally-index"
realm = "server"
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]
